import {useEffect,useState} from 'react';
import {Button,Card,Form,Input,Select,Space,Spin,Upload,message} from 'antd';
import type {UploadFile} from 'antd';
import {InboxOutlined} from '@ant-design/icons';
import {useNavigate,useParams,useLocation} from 'react-router-dom';
import PageHeader from '../../components/PageHeader';
import {dictionaryApi,type DictionaryPayload} from '../../services/dictionaryApi';
import type {Dictionary} from './data';

interface FormValues{code:string;name:string;valueType?:Dictionary['valueType'];remark?:string;source?:string;sortNo?:number}
export default function DictionaryForm(){
 const nav=useNavigate(),loc=useLocation();const {code,id}=useParams();const [form]=Form.useForm<FormValues>();const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [files,setFiles]=useState<UploadFile[]>([]);
 const isItem=loc.pathname.includes('/items/');const importing=loc.pathname.endsWith('/import');const editing=loc.pathname.endsWith('/edit');const back=isItem?`/app/system-config/dictionaries/${code}/items`:'/app/system-config/dictionaries';const title=`${importing?'导入':editing?'编辑':'创建'}${isItem?'字典项':'字典'}`;
 useEffect(()=>{if(!editing||!code)return;let active=true;setLoading(true);const detail=isItem&&id?dictionaryApi.itemDetail(code,id):dictionaryApi.detail(code);detail.then(data=>{if(active)form.setFieldsValue({code:data.code,name:data.name,remark:data.remark,...('valueType' in data?{valueType:data.valueType}:{sortNo:'sortNo' in data?data.sortNo:0})})}).catch(e=>message.error(e instanceof Error?e.message:'详情加载失败')).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[code,editing,form,id,isItem]);
 const save=async(values:FormValues)=>{if(!code&&isItem)return;setSaving(true);try{if(isItem&&code){const payload={code:values.code,name:values.name,remark:values.remark,sortNo:values.sortNo??0};if(editing&&id)await dictionaryApi.updateItem(code,id,payload);else await dictionaryApi.createItem(code,payload)}else{const payload=values as DictionaryPayload;if(editing&&code)await dictionaryApi.update(code,{...payload,code});else await dictionaryApi.create(payload)}message.success('保存成功');nav(back)}catch(e){message.error(e instanceof Error?e.message:'保存失败')}finally{setSaving(false)}};
 const importFile=async()=>{const file=files[0]?.originFileObj;if(!file)return void message.warning('请选择要导入的文件');if(!isItem||!code)return void message.warning('当前导入功能暂不可用');setSaving(true);try{const result=await dictionaryApi.importItems(code,file);message.success(`成功导入 ${result.imported} 个字典项`);nav(back)}catch(e){message.error(e instanceof Error?e.message:'导入失败')}finally{setSaving(false)}};
 return <div style={{padding:24,background:'#f5f7fa',minHeight:'100%'}}><PageHeader title={title} showBack onBack={()=>nav(back)} breadcrumb={[{path:'/app/system-config/dictionaries',breadcrumbName:'数据字典'},{path:'',breadcrumbName:title}]}/><Card style={{marginTop:16}}>{importing?<Form layout="vertical" style={{maxWidth:720}}><Form.Item label="上传文件" required extra="支持 xlsx、xls、csv 格式，单个文件不超过 30MB"><Upload.Dragger accept=".xlsx,.xls,.csv" maxCount={1} beforeUpload={()=>false} fileList={files} onChange={({fileList})=>setFiles(fileList)}><p><InboxOutlined style={{fontSize:38,color:'#1677ff'}}/></p><p>点击或将文件拖拽到此区域上传</p><p style={{color:'#999'}}>请确保编码唯一且必填字段完整</p></Upload.Dragger></Form.Item><Space><Button type="primary" loading={saving} onClick={()=>void importFile()}>保存</Button><Button onClick={()=>nav(back)}>取消</Button></Space></Form>:<Spin spinning={loading}><Form form={form} layout="vertical" style={{maxWidth:720}} initialValues={isItem?{sortNo:0}:{source:'自定义',valueType:'字符串'}} onFinish={save}><Form.Item name="code" label={isItem?'字典项编码':'字典编码'} rules={[{required:true,message:'请输入编码'},{pattern:/^[a-z][a-z0-9_]*$/,message:'请输入小写英文字母、数字或下划线'}]}><Input placeholder={isItem?'例如：follow_up':'例如：clinical_priority'} disabled={editing}/></Form.Item><Form.Item name="name" label={isItem?'字典项名称':'字典名称'} rules={[{required:true,message:'请输入名称'}]}><Input placeholder="请输入中文名称"/></Form.Item>{!isItem&&<>{!editing&&<Form.Item name="source" label="字典来源"><Input disabled/></Form.Item>}<Form.Item name="valueType" label="字典值类型" rules={[{required:true}]}><Select options={['字符串','整数','小数','日期'].map(value=>({value,label:value}))}/></Form.Item></>}<Form.Item name="remark" label="其他说明"><Input.TextArea rows={5} maxLength={500} showCount placeholder="请输入补充说明"/></Form.Item><Space><Button type="primary" htmlType="submit" loading={saving}>保存</Button><Button onClick={()=>nav(back)}>取消</Button></Space></Form></Spin>}</Card></div>
}
