import {useCallback,useEffect,useRef,useState} from 'react';
import {Button,Dropdown,Input,Modal,Space,Switch,Table,Tag,Typography,message} from 'antd';
import {DeleteOutlined,DownOutlined,EditOutlined,ExportOutlined,PlusOutlined,SearchOutlined} from '@ant-design/icons';
import {useNavigate,useParams} from 'react-router-dom';
import type {ColumnsType} from 'antd/es/table';
import PageHeader from '../../components/PageHeader';
import type {Dictionary,DictionaryItem} from './data';
import {dictionaryApi} from '../../services/dictionaryApi';
const {Text}=Typography;

export default function DictionaryItems(){
 const {code=''}=useParams();const nav=useNavigate();const [dict,setDict]=useState<Dictionary>();const [rows,setRows]=useState<DictionaryItem[]>([]);const [q,setQ]=useState('');const [loading,setLoading]=useState(false);const [current,setCurrent]=useState(1);const [pageSize,setPageSize]=useState(20);const [total,setTotal]=useState(0);const requestId=useRef(0);
 const load=useCallback(async()=>{const id=++requestId.current;setLoading(true);try{const data=await dictionaryApi.itemList(code,current,pageSize,q);if(id!==requestId.current)return;setDict(data.dictionary);setRows(data.list);setTotal(data.pagination.total)}catch(e){if(id===requestId.current)message.error(e instanceof Error?e.message:'字典项加载失败')}finally{if(id===requestId.current)setLoading(false)}},[code,current,pageSize,q]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),200);return()=>window.clearTimeout(timer)},[load]);
 const changeStatus=async(item:DictionaryItem,enabled:boolean)=>{try{await dictionaryApi.updateItemStatus(code,item.id,enabled);setRows(v=>v.map(x=>x.id===item.id?{...x,enabled}:x));message.success(enabled?'已启用':'已关闭')}catch(e){message.error(e instanceof Error?e.message:'状态更新失败');await load()}};
 const remove=(item:DictionaryItem)=>Modal.confirm({title:'确认是否删除？',content:`将删除字典项「${item.name}」`,okText:'确认删除',okType:'danger',cancelText:'取消',onOk:async()=>{try{await dictionaryApi.removeItem(code,item.id);message.success('删除成功');if(rows.length===1&&current>1)setCurrent(v=>v-1);else await load()}catch(e){message.error(e instanceof Error?e.message:'删除失败')}}});
 const exportItems=async()=>{try{await dictionaryApi.exportItems(code);message.success('字典项 Excel 已导出')}catch(e){message.error(e instanceof Error?e.message:'导出失败')}};
 const cols:ColumnsType<DictionaryItem>=[{title:'字典项编码',dataIndex:'code',width:220,render:v=><Text code>{v}</Text>},{title:'字典项名称',dataIndex:'name',width:220},{title:'状态',dataIndex:'enabled',width:110,render:(v,r)=><Switch checked={v} size="small" onChange={x=>void changeStatus(r,x)}/>},{title:'备注',dataIndex:'remark',render:v=>v||<Text type="secondary">-</Text>},{title:'操作',width:180,render:(_,r)=><Space><Button type="link" icon={<EditOutlined/>} onClick={()=>nav(`/app/system-config/dictionaries/${code}/items/${r.id}/edit`)}>编辑</Button><Button danger type="link" icon={<DeleteOutlined/>} onClick={()=>remove(r)}>删除</Button></Space>}];
 return <div style={{padding:24,background:'#f5f7fa',minHeight:'100%'}}><PageHeader title={`${dict?.name||code} · 字典项管理`} subTitle={`字典编码 ${code} ｜ 共 ${total} 项`} showBack onBack={()=>nav('/app/system-config/dictionaries')} breadcrumb={[{path:'/app/system-config/dictionaries',breadcrumbName:'数据字典'},{path:'',breadcrumbName:'字典项管理'}]} extra={<><Input prefix={<SearchOutlined/>} placeholder="搜索字典项" value={q} onChange={e=>{setQ(e.target.value);setCurrent(1)}} style={{width:220}}/><Button icon={<ExportOutlined/>} onClick={()=>void exportItems()}>导出字典项</Button><Dropdown menu={{items:[{key:'import',label:'导入字典项',onClick:()=>nav(`/app/system-config/dictionaries/${code}/items/import`)},{key:'create',label:'创建字典项',onClick:()=>nav(`/app/system-config/dictionaries/${code}/items/create`)}]}}><Button type="primary" icon={<PlusOutlined/>}>新增字典项 <DownOutlined/></Button></Dropdown></>}/><div style={{marginTop:16,padding:16,background:'#fff',borderRadius:8}}><Space style={{marginBottom:16}}><Tag color="blue">{dict?.source}</Tag><Text type="secondary">字典值类型：{dict?.valueType}</Text></Space><Table rowKey="id" columns={cols} dataSource={rows} loading={loading} pagination={{current,pageSize,total,onChange:(p,s)=>{setCurrent(p);setPageSize(s)}}}/></div></div>
}
