import { createCipheriv, createDecipheriv, createHash, randomBytes, randomUUID } from 'node:crypto';
import { Router } from 'express';
import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import { requireAuth } from '../auth.js';
import { config } from '../config.js';
import { pool } from '../db.js';
import { requirePermission } from '../middleware/authorization.js';

const router=Router();router.use(requireAuth,requirePermission('system:model'));
const ok=(data:unknown,message='success')=>({code:200,message,data,timestamp:new Date().toISOString()});
const fail=(statusCode:number,message:string)=>Object.assign(new Error(message),{statusCode});
const key=createHash('sha256').update(config.jwtSecret).digest();
const keyId='local-aes-gcm-v1';
const deploymentToDb={本地化部署:'LOCAL',云端部署:'CLOUD',混合部署:'HYBRID'} as const;
const deploymentToText:Record<string,string>={LOCAL:'本地化部署',CLOUD:'云端部署',HYBRID:'混合部署'};
const clean=(value:unknown)=>String(value??'').trim();
const masked=(last4:string)=>`••••••••${last4}`;
const isMasked=(value:string)=>/^[•*]{4,}\S{0,4}$/.test(value);

const encrypt=(plain:string)=>{const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',key,iv);const encrypted=Buffer.concat([cipher.update(plain,'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),encrypted])};
const decrypt=(payload:Buffer)=>{const iv=payload.subarray(0,12),tag=payload.subarray(12,28),encrypted=payload.subarray(28);const decipher=createDecipheriv('aes-256-gcm',key,iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(encrypted),decipher.final()]).toString('utf8')};

interface ModelInput{name:string;version:string;deployment:keyof typeof deploymentToDb;apiUrl:string;apiKey:string;provider:string;phone:string;remark?:string}
const validate=(body:Record<string,unknown>,editing=false):ModelInput|string=>{const input={name:clean(body.name),version:clean(body.version),deployment:clean(body.deployment) as keyof typeof deploymentToDb,apiUrl:clean(body.apiUrl),apiKey:clean(body.apiKey),provider:clean(body.provider),phone:clean(body.phone),remark:clean(body.remark)||undefined};if(!input.name||input.name.length>100)return'模型名称不能为空且不能超过100个字符';if(!input.version||input.version.length>50)return'模型版本号不能为空且不能超过50个字符';if(!(input.deployment in deploymentToDb))return'部署方式不正确';try{const url=new URL(input.apiUrl);if(!['http:','https:'].includes(url.protocol)||input.apiUrl.length>1000)throw new Error()}catch{return'请输入正确的 API 地址'}if((!editing||!isMasked(input.apiKey))&&(!input.apiKey||input.apiKey.length>1000))return'API key不能为空且不能超过1000个字符';if(input.provider.length>100)return'提供方不能超过100个字符';if(input.phone&&!/^1\d{10}$/.test(input.phone))return'请输入正确的 11 位手机号';if((input.remark?.length??0)>500)return'其他说明不能超过500个字符';return input};

const dto=(row:RowDataPacket)=>({id:row.model_uuid,name:row.model_name,version:row.model_version,deployment:deploymentToText[row.deployment_mode]??row.deployment_mode,apiUrl:row.api_url,apiKey:masked(row.api_key_last4),provider:row.provider_name,phone:row.contact_phone,remark:row.remark??undefined,connected:row.connection_status==='PASSED',connectionStatus:row.connection_status,lastTestedAt:row.last_tested_at?String(row.last_tested_at).slice(0,19):undefined});
const select=`SELECT m.* FROM sys_model_config m`;
const providerId=async(provider:string)=>{if(!provider)return null;const[rows]=await pool.execute<RowDataPacket[]>(`SELECT id FROM iam_user WHERE real_name=? AND is_deleted=0 LIMIT 1`,[provider]);return rows[0]?.id??null};

const runConnectionTest=async(apiUrl:string,apiKey:string)=>{const started=Date.now();const target=apiUrl.replace(/\/+$/,'').endsWith('/models')?apiUrl.replace(/\/+$/,''):`${apiUrl.replace(/\/+$/,'')}/models`;try{const response=await fetch(target,{method:'GET',headers:{Authorization:`Bearer ${apiKey}`,Accept:'application/json'},signal:AbortSignal.timeout(10_000)});const latencyMs=Date.now()-started;if(!response.ok){const detail=(await response.text()).slice(0,500);return{passed:false,httpStatus:response.status,latencyMs,errorCode:`HTTP_${response.status}`,errorMessage:detail||response.statusText}}return{passed:true,httpStatus:response.status,latencyMs}}catch(error){const timeout=error instanceof Error&&(error.name==='TimeoutError'||error.name==='AbortError');return{passed:false,httpStatus:null,latencyMs:Date.now()-started,errorCode:timeout?'TIMEOUT':'CONNECTION_ERROR',errorMessage:timeout?'连接超时（10秒）':error instanceof Error?error.message:'连接失败'}}};

router.get('/',async(req,res,next)=>{try{const current=Math.max(1,Number(req.query.current)||1),pageSize=Math.min(100,Math.max(1,Number(req.query.pageSize)||10));const[totalRows]=await pool.execute<RowDataPacket[]>(`SELECT COUNT(*) total FROM sys_model_config WHERE is_deleted=0`);const[rows]=await pool.query<RowDataPacket[]>(`${select} WHERE m.is_deleted=0 ORDER BY m.created_at DESC,m.id DESC LIMIT ? OFFSET ?`,[pageSize,(current-1)*pageSize]);res.json(ok({list:rows.map(dto),pagination:{current,pageSize,total:Number(totalRows[0]!.total)}}))}catch(e){next(e)}});

router.post('/test-connection',async(req,res,next)=>{try{const input=validate(req.body??{},true);if(typeof input==='string')return void res.status(400).json({code:400,message:input});let apiKey=input.apiKey;if(isMasked(apiKey)){const modelId=clean(req.body?.id);const[models]=await pool.execute<RowDataPacket[]>(`SELECT api_key_ciphertext FROM sys_model_config WHERE model_uuid=? AND is_deleted=0`,[modelId]);if(!models.length)return void res.status(400).json({code:400,message:'模型配置不存在，无法使用已保存的 API key'});apiKey=decrypt(Buffer.from(models[0]!.api_key_ciphertext))}const result=await runConnectionTest(input.apiUrl,apiKey);if(!result.passed)return void res.status(422).json({code:422,message:`测试验证异常：${result.errorCode} ${result.errorMessage}`,data:result});res.json(ok(result,'测试验证正常'))}catch(e){next(e)}});

router.post('/',async(req,res,next)=>{const input=validate(req.body??{});if(typeof input==='string')return void res.status(400).json({code:400,message:input});const connection=await pool.getConnection();try{await connection.beginTransaction();const provider=await providerId(input.provider);const[result]=await connection.execute<ResultSetHeader>(`INSERT INTO sys_model_config(model_uuid,model_name,model_version,deployment_mode,api_url,api_key_ciphertext,api_key_key_id,api_key_last4,provider_user_id,provider_name,contact_phone,remark,connection_status,created_by,updated_by)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[randomUUID(),input.name,input.version,deploymentToDb[input.deployment],input.apiUrl,encrypt(input.apiKey),keyId,input.apiKey.slice(-4).padStart(4,'*'),provider,input.provider,input.phone,input.remark??null,req.body?.connected===true?'PASSED':'NOT_TESTED',req.auth!.userId,req.auth!.userId]);await connection.commit();res.status(201).json(ok({id:String(result.insertId)},'模型配置创建成功'))}catch(error:any){await connection.rollback();if(error?.errno===1062)return void res.status(409).json({code:409,message:'相同名称和版本的模型已存在'});next(error)}finally{connection.release()}});

router.get('/:id',async(req,res,next)=>{try{const[rows]=await pool.execute<RowDataPacket[]>(`${select} WHERE m.model_uuid=? AND m.is_deleted=0`,[req.params.id]);if(!rows.length)return void res.status(404).json({code:404,message:'模型配置不存在'});res.json(ok(dto(rows[0]!)))}catch(e){next(e)}});

router.put('/:id',async(req,res,next)=>{const input=validate(req.body??{},true);if(typeof input==='string')return void res.status(400).json({code:400,message:input});try{const[models]=await pool.execute<RowDataPacket[]>(`SELECT id,api_key_ciphertext,api_key_last4 FROM sys_model_config WHERE model_uuid=? AND is_deleted=0`,[req.params.id]);if(!models.length)return void res.status(404).json({code:404,message:'模型配置不存在'});const preserve=isMasked(input.apiKey);const cipher=preserve?models[0]!.api_key_ciphertext:encrypt(input.apiKey),last4=preserve?models[0]!.api_key_last4:input.apiKey.slice(-4).padStart(4,'*');await pool.execute(`UPDATE sys_model_config SET model_name=?,model_version=?,deployment_mode=?,api_url=?,api_key_ciphertext=?,api_key_key_id=?,api_key_last4=?,provider_user_id=?,provider_name=?,contact_phone=?,remark=?,connection_status=?,updated_by=? WHERE id=?`,[input.name,input.version,deploymentToDb[input.deployment],input.apiUrl,cipher,keyId,last4,await providerId(input.provider),input.provider,input.phone,input.remark??null,req.body?.connected===true?'PASSED':'NOT_TESTED',req.auth!.userId,models[0]!.id]);res.json(ok(null,'模型配置更新成功'))}catch(error:any){if(error?.errno===1062)return void res.status(409).json({code:409,message:'相同名称和版本的模型已存在'});next(error)}});

router.post('/:id/test',async(req,res,next)=>{try{const[models]=await pool.execute<RowDataPacket[]>(`SELECT id,api_url,api_key_ciphertext FROM sys_model_config WHERE model_uuid=? AND is_deleted=0`,[req.params.id]);if(!models.length)return void res.status(404).json({code:404,message:'模型配置不存在'});const model=models[0]!;const[result]=await pool.execute<ResultSetHeader>(`INSERT INTO sys_model_connection_test(model_config_id,test_result,tested_by)VALUES(?,'RUNNING',?)`,[model.id,req.auth!.userId]);let apiKey:string;try{apiKey=decrypt(Buffer.from(model.api_key_ciphertext))}catch{throw fail(500,'API key 解密失败')};const test=await runConnectionTest(model.api_url,apiKey);await pool.execute(`UPDATE sys_model_connection_test SET test_result=?,http_status=?,latency_ms=?,error_code=?,error_message=?,finished_at=CURRENT_TIMESTAMP(3) WHERE id=?`,[test.passed?'PASSED':'FAILED',test.httpStatus,test.latencyMs,test.errorCode??null,test.errorMessage??null,result.insertId]);await pool.execute(`UPDATE sys_model_config SET connection_status=?,last_tested_at=CURRENT_TIMESTAMP(3),updated_by=? WHERE id=?`,[test.passed?'PASSED':'FAILED',req.auth!.userId,model.id]);if(!test.passed)return void res.status(422).json({code:422,message:`测试验证异常：${test.errorCode} ${test.errorMessage}`,data:test});res.json(ok(test,'测试验证正常'))}catch(e){next(e)}});

router.delete('/:id',async(req,res,next)=>{try{const[result]=await pool.execute<ResultSetHeader>(`DELETE FROM sys_model_config WHERE model_uuid=?`,[req.params.id]);if(!result.affectedRows)return void res.status(404).json({code:404,message:'模型配置不存在'});res.json(ok(null,'模型配置删除成功'))}catch(e){next(e)}});

export default router;
