-- ============================================================================
-- 医疗智能体管理平台：表与字段中文备注修复脚本
-- 版本：V1.0.1
-- 前置版本：V1.0
-- 目标数据库：MySQL 9.7.0
-- 说明：补齐43张表的表级备注及437个字段的字段级备注，不修改业务数据。
-- ============================================================================

SET NAMES utf8mb4;
SET time_zone = '+08:00';
USE `med_agent_platform`;

-- 1. 统一刷新表级中文备注
ALTER TABLE `sys_schema_version` COMMENT = '数据库版本记录';
ALTER TABLE `sys_department` COMMENT = '医院组织/科室';
ALTER TABLE `sys_file_object` COMMENT = '统一文件对象元数据';
ALTER TABLE `iam_user` COMMENT = '平台用户';
ALTER TABLE `iam_user_password` COMMENT = '用户密码凭据与锁定状态';
ALTER TABLE `iam_sms_verification_code` COMMENT = '短信验证码';
ALTER TABLE `iam_login_session` COMMENT = '用户登录会话';
ALTER TABLE `iam_login_log` COMMENT = '登录审计日志';
ALTER TABLE `iam_role` COMMENT = '角色';
ALTER TABLE `iam_user_role` COMMENT = '用户角色关联';
ALTER TABLE `iam_permission` COMMENT = '功能权限树';
ALTER TABLE `iam_role_permission` COMMENT = '角色功能权限';
ALTER TABLE `iam_hr_sync_batch` COMMENT = '医院员工/组织同步批次';
ALTER TABLE `iam_hr_sync_item` COMMENT = '医院员工同步明细';
ALTER TABLE `agt_agent` COMMENT = '智能体统一主数据';
ALTER TABLE `agt_agent_clinical_stage` COMMENT = '智能体诊疗环节';
ALTER TABLE `agt_registration_application` COMMENT = '智能体接入申请';
ALTER TABLE `agt_registration_revision` COMMENT = '接入申请修订快照';
ALTER TABLE `agt_registration_model` COMMENT = '接入申请使用模型配置';
ALTER TABLE `agt_registration_file` COMMENT = '接入备案材料';
ALTER TABLE `agt_access_config` COMMENT = '接入地址与加密凭据';
ALTER TABLE `agt_connection_test` COMMENT = '接入连通测试记录';
ALTER TABLE `agt_registration_review` COMMENT = '接入审核结论';
ALTER TABLE `agt_registration_status_history` COMMENT = '接入申请状态轨迹';
ALTER TABLE `agt_agent_document` COMMENT = '智能体当前备案材料映射';
ALTER TABLE `iam_data_policy` COMMENT = '数据权限策略';
ALTER TABLE `iam_role_data_policy` COMMENT = '角色数据策略绑定';
ALTER TABLE `iam_department_data_policy` COMMENT = '组织数据策略绑定';
ALTER TABLE `iam_user_data_policy` COMMENT = '用户级数据权限覆盖';
ALTER TABLE `iam_data_policy_department_scope` COMMENT = '数据策略指定科室范围';
ALTER TABLE `iam_data_policy_agent_scope` COMMENT = '数据策略指定智能体范围';
ALTER TABLE `iam_data_policy_classification` COMMENT = '数据策略可见数据分级';
ALTER TABLE `led_agent_ledger` COMMENT = '智能体统一台账管理状态';
ALTER TABLE `led_agent_version` COMMENT = '智能体版本历史';
ALTER TABLE `led_lifecycle_event` COMMENT = '台账生命周期与状态变更时间线';
ALTER TABLE `led_risk_question` COMMENT = '风险分级问卷题目';
ALTER TABLE `led_risk_option` COMMENT = '风险分级问卷选项';
ALTER TABLE `led_risk_assessment` COMMENT = '智能体风险分级评定';
ALTER TABLE `led_risk_answer` COMMENT = '风险分级问卷作答';
ALTER TABLE `led_resource_link` COMMENT = '台账已对接资源引用/快照';
ALTER TABLE `led_evaluation_ref` COMMENT = '台账评测报告引用及查询快照';
ALTER TABLE `led_metric_snapshot` COMMENT = '台账运行指标查询快照';
ALTER TABLE `integration_outbox_event` COMMENT = '跨模块可靠事件发件箱';

-- 2. 补齐V1.0中缺失的字段级中文备注
ALTER TABLE `agt_access_config`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `revision_id` BIGINT UNSIGNED NOT NULL COMMENT '关联接入申请修订主键',
  MODIFY COLUMN `access_mode` VARCHAR(20) NOT NULL COMMENT '接入方式：API、SDK或OTel',
  MODIFY COLUMN `expires_at` DATETIME(3) NULL COMMENT '接入凭据过期时间',
  MODIFY COLUMN `rotated_at` DATETIME(3) NULL COMMENT '接入密钥最近轮换时间',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间',
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '记录最后更新时间';

ALTER TABLE `agt_agent`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `agent_version` VARCHAR(30) NOT NULL COMMENT '智能体版本号',
  MODIFY COLUMN `department_id` BIGINT UNSIGNED NOT NULL COMMENT '关联科室主键',
  MODIFY COLUMN `supplier_name` VARCHAR(100) NULL COMMENT '供应商全称',
  MODIFY COLUMN `function_description` VARCHAR(500) NOT NULL COMMENT '智能体核心功能与应用场景说明',
  MODIFY COLUMN `tech_contact_name` VARCHAR(50) NOT NULL COMMENT '技术联系人姓名',
  MODIFY COLUMN `tech_contact_phone` VARCHAR(20) NOT NULL COMMENT '技术联系人手机号',
  MODIFY COLUMN `tech_contact_email` VARCHAR(254) NULL COMMENT '技术联系人邮箱',
  MODIFY COLUMN `created_by` BIGINT UNSIGNED NOT NULL COMMENT '创建人用户主键',
  MODIFY COLUMN `updated_by` BIGINT UNSIGNED NOT NULL COMMENT '最后更新人用户主键',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间',
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '记录最后更新时间',
  MODIFY COLUMN `is_deleted` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '逻辑删除标记：FALSE未删除，TRUE已删除';

ALTER TABLE `agt_agent_clinical_stage`
  MODIFY COLUMN `agent_id` BIGINT UNSIGNED NOT NULL COMMENT '关联智能体主键',
  MODIFY COLUMN `stage_name` VARCHAR(50) NOT NULL COMMENT '诊疗环节名称',
  MODIFY COLUMN `sort_no` INT NOT NULL DEFAULT 0 COMMENT '显示排序号';

ALTER TABLE `agt_agent_document`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `agent_id` BIGINT UNSIGNED NOT NULL COMMENT '关联智能体主键',
  MODIFY COLUMN `file_id` BIGINT UNSIGNED NOT NULL COMMENT '关联文件对象主键',
  MODIFY COLUMN `is_current` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否为智能体当前有效材料',
  MODIFY COLUMN `sort_no` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '显示排序号',
  MODIFY COLUMN `created_by` BIGINT UNSIGNED NULL COMMENT '维护材料的用户主键',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间';

ALTER TABLE `agt_connection_test`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `revision_id` BIGINT UNSIGNED NOT NULL COMMENT '关联接入申请修订主键',
  MODIFY COLUMN `http_status` SMALLINT UNSIGNED NULL COMMENT '连通测试HTTP状态码',
  MODIFY COLUMN `latency_ms` INT UNSIGNED NULL COMMENT '连通测试响应耗时（毫秒）',
  MODIFY COLUMN `error_code` VARCHAR(100) NULL COMMENT '连通测试错误代码',
  MODIFY COLUMN `error_message` VARCHAR(1000) NULL COMMENT '错误详细信息',
  MODIFY COLUMN `tested_by` BIGINT UNSIGNED NOT NULL COMMENT '执行连通测试的用户主键',
  MODIFY COLUMN `started_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '处理开始时间',
  MODIFY COLUMN `finished_at` DATETIME(3) NULL COMMENT '处理完成时间';

ALTER TABLE `agt_registration_application`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `agent_id` BIGINT UNSIGNED NOT NULL COMMENT '关联智能体主键',
  MODIFY COLUMN `applicant_id` BIGINT UNSIGNED NOT NULL COMMENT '申请人用户主键',
  MODIFY COLUMN `current_revision_no` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '当前生效的申请修订序号',
  MODIFY COLUMN `submitted_at` DATETIME(3) NULL COMMENT '提交时间',
  MODIFY COLUMN `review_started_at` DATETIME(3) NULL COMMENT '审核开始时间',
  MODIFY COLUMN `withdrawn_at` DATETIME(3) NULL COMMENT '申请撤销时间',
  MODIFY COLUMN `returned_at` DATETIME(3) NULL COMMENT '审核退回时间',
  MODIFY COLUMN `approved_at` DATETIME(3) NULL COMMENT '审核通过时间',
  MODIFY COLUMN `ledger_synced_at` DATETIME(3) NULL COMMENT '审核结果同步至台账的时间',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '接入申请创建时间',
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '接入申请最后更新时间';

ALTER TABLE `agt_registration_file`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `revision_id` BIGINT UNSIGNED NOT NULL COMMENT '关联接入申请修订主键',
  MODIFY COLUMN `file_id` BIGINT UNSIGNED NOT NULL COMMENT '关联文件对象主键',
  MODIFY COLUMN `sort_no` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '显示排序号',
  MODIFY COLUMN `ocr_status` VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'OCR识别状态',
  MODIFY COLUMN `ocr_structured_data` JSON NULL COMMENT 'OCR识别后的结构化数据（JSON）',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间';

ALTER TABLE `agt_registration_model`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `revision_id` BIGINT UNSIGNED NOT NULL COMMENT '关联接入申请修订主键',
  MODIFY COLUMN `sort_no` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '显示排序号',
  MODIFY COLUMN `model_name` VARCHAR(100) NOT NULL COMMENT '模型名称',
  MODIFY COLUMN `model_version` VARCHAR(50) NOT NULL COMMENT '模型版本号',
  MODIFY COLUMN `parameter_count` DECIMAL(12,1) UNSIGNED NULL COMMENT '模型参数量（单位：十亿/B）',
  MODIFY COLUMN `is_open_source` BOOLEAN NULL COMMENT '模型是否开源',
  MODIFY COLUMN `context_length` INT UNSIGNED NULL COMMENT '模型上下文窗口长度',
  MODIFY COLUMN `temperature` DECIMAL(6,4) NULL COMMENT '模型采样温度参数',
  MODIFY COLUMN `top_p` DECIMAL(6,4) NULL COMMENT '模型Top-P采样参数',
  MODIFY COLUMN `max_concurrency` INT UNSIGNED NULL COMMENT '模型最大并发数',
  MODIFY COLUMN `release_date` DATE NULL COMMENT '模型发布日期';

ALTER TABLE `agt_registration_review`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `application_id` BIGINT UNSIGNED NOT NULL COMMENT '被审核的接入申请主键',
  MODIFY COLUMN `reviewer_id` BIGINT UNSIGNED NOT NULL COMMENT '审核人用户主键',
  MODIFY COLUMN `reviewed_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '审核完成时间';

ALTER TABLE `agt_registration_revision`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `application_id` BIGINT UNSIGNED NOT NULL COMMENT '关联接入申请主键',
  MODIFY COLUMN `revision_no` INT UNSIGNED NOT NULL COMMENT '申请修订序号',
  MODIFY COLUMN `agent_name` VARCHAR(100) NOT NULL COMMENT '智能体名称',
  MODIFY COLUMN `agent_code` VARCHAR(50) NOT NULL COMMENT '智能体业务编号',
  MODIFY COLUMN `agent_version` VARCHAR(30) NOT NULL COMMENT '智能体版本号',
  MODIFY COLUMN `department_id` BIGINT UNSIGNED NOT NULL COMMENT '关联科室主键',
  MODIFY COLUMN `agent_type` VARCHAR(50) NULL COMMENT '智能体类型',
  MODIFY COLUMN `source_type` VARCHAR(20) NULL COMMENT '智能体来源类型',
  MODIFY COLUMN `supplier_name` VARCHAR(100) NULL COMMENT '供应商全称',
  MODIFY COLUMN `function_description` VARCHAR(500) NOT NULL COMMENT '智能体核心功能与应用场景说明',
  MODIFY COLUMN `tech_contact_name` VARCHAR(50) NOT NULL COMMENT '技术联系人姓名',
  MODIFY COLUMN `tech_contact_phone` VARCHAR(20) NOT NULL COMMENT '技术联系人手机号',
  MODIFY COLUMN `tech_contact_email` VARCHAR(254) NULL COMMENT '技术联系人邮箱',
  MODIFY COLUMN `access_mode` VARCHAR(20) NOT NULL COMMENT '接入方式：API、SDK或OTel',
  MODIFY COLUMN `change_summary` VARCHAR(500) NULL COMMENT '本次修订内容摘要',
  MODIFY COLUMN `created_by` BIGINT UNSIGNED NOT NULL COMMENT '创建该修订的用户主键',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '申请修订创建时间';

ALTER TABLE `agt_registration_status_history`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `application_id` BIGINT UNSIGNED NOT NULL COMMENT '关联接入申请主键',
  MODIFY COLUMN `revision_id` BIGINT UNSIGNED NULL COMMENT '关联接入申请修订主键',
  MODIFY COLUMN `from_status` VARCHAR(30) NULL COMMENT '变更前状态',
  MODIFY COLUMN `to_status` VARCHAR(30) NOT NULL COMMENT '变更后状态',
  MODIFY COLUMN `operator_name_snapshot` VARCHAR(100) NULL COMMENT '状态变更操作人姓名快照',
  MODIFY COLUMN `remark` VARCHAR(500) NULL COMMENT '状态流转原因或补充说明',
  MODIFY COLUMN `occurred_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '事件发生时间';

ALTER TABLE `iam_data_policy`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `policy_code` VARCHAR(64) NOT NULL COMMENT '数据权限策略编码',
  MODIFY COLUMN `policy_name` VARCHAR(150) NOT NULL COMMENT '数据权限策略名称',
  MODIFY COLUMN `description` VARCHAR(500) NULL COMMENT '数据权限策略说明',
  MODIFY COLUMN `status` VARCHAR(20) NOT NULL DEFAULT 'ENABLED' COMMENT '数据权限策略状态：ENABLED启用、DISABLED停用',
  MODIFY COLUMN `created_by` BIGINT UNSIGNED NULL COMMENT '创建人用户主键',
  MODIFY COLUMN `updated_by` BIGINT UNSIGNED NULL COMMENT '最后更新人用户主键',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间',
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '记录最后更新时间',
  MODIFY COLUMN `is_deleted` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '逻辑删除标记：FALSE未删除，TRUE已删除';

ALTER TABLE `iam_data_policy_agent_scope`
  MODIFY COLUMN `policy_id` BIGINT UNSIGNED NOT NULL COMMENT '关联数据权限策略主键',
  MODIFY COLUMN `agent_id` BIGINT UNSIGNED NOT NULL COMMENT '关联智能体主键';

ALTER TABLE `iam_data_policy_classification`
  MODIFY COLUMN `policy_id` BIGINT UNSIGNED NOT NULL COMMENT '关联数据权限策略主键';

ALTER TABLE `iam_data_policy_department_scope`
  MODIFY COLUMN `policy_id` BIGINT UNSIGNED NOT NULL COMMENT '关联数据权限策略主键',
  MODIFY COLUMN `department_id` BIGINT UNSIGNED NOT NULL COMMENT '关联科室主键';

ALTER TABLE `iam_department_data_policy`
  MODIFY COLUMN `department_id` BIGINT UNSIGNED NOT NULL COMMENT '关联科室主键',
  MODIFY COLUMN `policy_id` BIGINT UNSIGNED NOT NULL COMMENT '关联数据权限策略主键',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间';

ALTER TABLE `iam_hr_sync_batch`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `batch_no` VARCHAR(64) NOT NULL COMMENT '同步批次编号',
  MODIFY COLUMN `added_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '本批次新增用户数量',
  MODIFY COLUMN `updated_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '本批次更新用户数量',
  MODIFY COLUMN `disabled_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '本批次停用用户数量',
  MODIFY COLUMN `failed_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '本批次处理失败数量',
  MODIFY COLUMN `message` VARCHAR(1000) NULL COMMENT '本次员工同步结果摘要',
  MODIFY COLUMN `started_by` BIGINT UNSIGNED NULL COMMENT '发起同步的用户主键',
  MODIFY COLUMN `started_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '处理开始时间',
  MODIFY COLUMN `finished_at` DATETIME(3) NULL COMMENT '处理完成时间';

ALTER TABLE `iam_hr_sync_item`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `batch_id` BIGINT UNSIGNED NOT NULL COMMENT '关联同步批次主键',
  MODIFY COLUMN `external_employee_no` VARCHAR(50) NOT NULL COMMENT '医院员工系统工号',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NULL COMMENT '关联用户主键',
  MODIFY COLUMN `before_data` JSON NULL COMMENT '同步前的用户数据快照（JSON）',
  MODIFY COLUMN `after_data` JSON NULL COMMENT '同步后的用户数据快照（JSON）',
  MODIFY COLUMN `error_message` VARCHAR(1000) NULL COMMENT '单条员工数据同步失败原因',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间';

ALTER TABLE `iam_login_log`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NULL COMMENT '关联用户主键',
  MODIFY COLUMN `failure_reason` VARCHAR(200) NULL COMMENT '登录失败原因',
  MODIFY COLUMN `ip_address` VARCHAR(45) NULL COMMENT '客户端IP地址（IPv4或IPv6）',
  MODIFY COLUMN `user_agent` VARCHAR(500) NULL COMMENT '客户端User-Agent信息',
  MODIFY COLUMN `device_id` VARCHAR(128) NULL COMMENT '客户端设备标识',
  MODIFY COLUMN `occurred_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '事件发生时间';

ALTER TABLE `iam_login_session`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `session_uuid` CHAR(36) NOT NULL COMMENT '登录会话全局唯一标识',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL COMMENT '关联用户主键',
  MODIFY COLUMN `device_id` VARCHAR(128) NULL COMMENT '客户端设备标识',
  MODIFY COLUMN `ip_address` VARCHAR(45) NULL COMMENT '客户端IP地址（IPv4或IPv6）',
  MODIFY COLUMN `user_agent` VARCHAR(500) NULL COMMENT '客户端User-Agent信息',
  MODIFY COLUMN `expires_at` DATETIME(3) NOT NULL COMMENT '登录会话过期时间',
  MODIFY COLUMN `last_active_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '会话最后活跃时间',
  MODIFY COLUMN `revoked_at` DATETIME(3) NULL COMMENT '会话撤销时间',
  MODIFY COLUMN `revoke_reason` VARCHAR(200) NULL COMMENT '会话撤销原因',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间';

ALTER TABLE `iam_permission`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `parent_id` BIGINT UNSIGNED NULL COMMENT '父级权限主键',
  MODIFY COLUMN `permission_name` VARCHAR(150) NOT NULL COMMENT '功能权限名称',
  MODIFY COLUMN `route_path` VARCHAR(255) NULL COMMENT '前端页面路由',
  MODIFY COLUMN `sort_no` INT NOT NULL DEFAULT 0 COMMENT '显示排序号',
  MODIFY COLUMN `status` VARCHAR(20) NOT NULL DEFAULT 'ENABLED' COMMENT '功能权限状态：ENABLED启用、DISABLED停用',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间',
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '记录最后更新时间';

ALTER TABLE `iam_role`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `role_code` VARCHAR(64) NOT NULL COMMENT '角色唯一编码',
  MODIFY COLUMN `role_name` VARCHAR(100) NOT NULL COMMENT '角色名称',
  MODIFY COLUMN `description` VARCHAR(500) NULL COMMENT '角色职责说明',
  MODIFY COLUMN `created_by` BIGINT UNSIGNED NULL COMMENT '创建人用户主键',
  MODIFY COLUMN `updated_by` BIGINT UNSIGNED NULL COMMENT '最后更新人用户主键',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间',
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '记录最后更新时间',
  MODIFY COLUMN `is_deleted` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '角色逻辑删除标记：FALSE未删除，TRUE已删除';

ALTER TABLE `iam_role_data_policy`
  MODIFY COLUMN `role_id` BIGINT UNSIGNED NOT NULL COMMENT '关联角色主键',
  MODIFY COLUMN `policy_id` BIGINT UNSIGNED NOT NULL COMMENT '关联数据权限策略主键',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间';

ALTER TABLE `iam_role_permission`
  MODIFY COLUMN `role_id` BIGINT UNSIGNED NOT NULL COMMENT '关联角色主键',
  MODIFY COLUMN `permission_id` BIGINT UNSIGNED NOT NULL COMMENT '关联功能权限主键',
  MODIFY COLUMN `granted_by` BIGINT UNSIGNED NULL COMMENT '授予功能权限的用户主键',
  MODIFY COLUMN `granted_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '授权时间';

ALTER TABLE `iam_sms_verification_code`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `phone` VARCHAR(20) NOT NULL COMMENT '接收短信验证码的手机号',
  MODIFY COLUMN `consumed_at` DATETIME(3) NULL COMMENT '验证码核销时间',
  MODIFY COLUMN `verify_attempts` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '验证码校验失败次数',
  MODIFY COLUMN `request_ip` VARCHAR(45) NULL COMMENT '验证码请求来源IP地址',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间';

ALTER TABLE `iam_user`
  MODIFY COLUMN `last_login_at` DATETIME(3) NULL COMMENT '用户最后登录时间',
  MODIFY COLUMN `last_login_ip` VARCHAR(45) NULL COMMENT '用户最后登录IP地址',
  MODIFY COLUMN `created_by` BIGINT UNSIGNED NULL COMMENT '创建人用户主键',
  MODIFY COLUMN `updated_by` BIGINT UNSIGNED NULL COMMENT '最后更新人用户主键',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间',
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '记录最后更新时间',
  MODIFY COLUMN `is_deleted` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '逻辑删除标记：FALSE未删除，TRUE已删除';

ALTER TABLE `iam_user_data_policy`
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL COMMENT '关联用户主键',
  MODIFY COLUMN `policy_id` BIGINT UNSIGNED NOT NULL COMMENT '关联数据权限策略主键',
  MODIFY COLUMN `override_reason` VARCHAR(500) NOT NULL COMMENT '用户级权限覆盖原因',
  MODIFY COLUMN `expires_at` DATETIME(3) NULL COMMENT '用户级权限覆盖到期时间',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间',
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '记录最后更新时间';

ALTER TABLE `iam_user_password`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL COMMENT '关联用户主键',
  MODIFY COLUMN `password_algorithm` VARCHAR(30) NOT NULL DEFAULT 'ARGON2ID' COMMENT '密码哈希算法',
  MODIFY COLUMN `password_version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '密码凭据版本号',
  MODIFY COLUMN `password_changed_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '最近一次密码修改时间',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间',
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '记录最后更新时间';

ALTER TABLE `iam_user_role`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL COMMENT '关联用户主键',
  MODIFY COLUMN `role_id` BIGINT UNSIGNED NOT NULL COMMENT '关联角色主键',
  MODIFY COLUMN `granted_by` BIGINT UNSIGNED NULL COMMENT '执行授权的用户主键',
  MODIFY COLUMN `granted_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '授权时间',
  MODIFY COLUMN `expires_at` DATETIME(3) NULL COMMENT '用户角色授权到期时间';

ALTER TABLE `integration_outbox_event`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `event_uuid` CHAR(36) NOT NULL COMMENT '事件全局唯一标识',
  MODIFY COLUMN `aggregate_id` VARCHAR(100) NOT NULL COMMENT '聚合根业务标识',
  MODIFY COLUMN `payload` JSON NOT NULL COMMENT '待发布事件载荷（JSON）',
  MODIFY COLUMN `retry_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '事件发布重试次数',
  MODIFY COLUMN `next_retry_at` DATETIME(3) NULL COMMENT '事件下次重试时间',
  MODIFY COLUMN `published_at` DATETIME(3) NULL COMMENT '事件成功发布时间',
  MODIFY COLUMN `last_error` VARCHAR(1000) NULL COMMENT '最近一次发布失败原因',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间';

ALTER TABLE `led_agent_ledger`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `runtime_exception_reason` VARCHAR(500) NULL COMMENT '运行异常原因',
  MODIFY COLUMN `online_at` DATETIME(3) NULL COMMENT '智能体正式上线时间',
  MODIFY COLUMN `trial_expires_at` DATETIME(3) NULL COMMENT '试运行到期时间',
  MODIFY COLUMN `disabled_at` DATETIME(3) NULL COMMENT '智能体禁用时间',
  MODIFY COLUMN `disabled_by` BIGINT UNSIGNED NULL COMMENT '执行禁用的用户主键',
  MODIFY COLUMN `disabled_reason` VARCHAR(200) NULL COMMENT '智能体禁用原因',
  MODIFY COLUMN `last_heartbeat_at` DATETIME(3) NULL COMMENT '运行监控最近心跳时间',
  MODIFY COLUMN `row_version` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间',
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '记录最后更新时间';

ALTER TABLE `led_agent_version`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `agent_id` BIGINT UNSIGNED NOT NULL COMMENT '关联智能体主键',
  MODIFY COLUMN `version_no` VARCHAR(30) NOT NULL COMMENT '版本号',
  MODIFY COLUMN `source_revision_id` BIGINT UNSIGNED NULL COMMENT '来源接入申请修订主键',
  MODIFY COLUMN `evaluation_report_ref` VARCHAR(100) NULL COMMENT '关联评测报告业务标识',
  MODIFY COLUMN `online_at` DATETIME(3) NOT NULL COMMENT '该版本上线时间',
  MODIFY COLUMN `offline_at` DATETIME(3) NULL COMMENT '版本下线时间',
  MODIFY COLUMN `version_description` VARCHAR(500) NULL COMMENT '版本变更说明',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间';

ALTER TABLE `led_evaluation_ref`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `agent_id` BIGINT UNSIGNED NOT NULL COMMENT '关联智能体主键',
  MODIFY COLUMN `agent_version` VARCHAR(30) NOT NULL COMMENT '智能体版本号',
  MODIFY COLUMN `external_task_id` VARCHAR(100) NOT NULL COMMENT '评测中心任务业务标识',
  MODIFY COLUMN `external_report_id` VARCHAR(100) NOT NULL COMMENT '评测中心报告业务标识',
  MODIFY COLUMN `total_score` DECIMAL(6,2) NOT NULL COMMENT '评测结果总分（0至100）',
  MODIFY COLUMN `report_url` VARCHAR(1000) NULL COMMENT '评测报告访问地址',
  MODIFY COLUMN `is_current` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否为该智能体当前评测结果',
  MODIFY COLUMN `evaluated_at` DATETIME(3) NOT NULL COMMENT '评测完成时间',
  MODIFY COLUMN `synced_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '数据最近同步时间';

ALTER TABLE `led_lifecycle_event`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `ledger_id` BIGINT UNSIGNED NOT NULL COMMENT '关联台账记录主键',
  MODIFY COLUMN `from_status` VARCHAR(30) NULL COMMENT '生命周期变更前状态',
  MODIFY COLUMN `to_status` VARCHAR(30) NULL COMMENT '生命周期变更后状态',
  MODIFY COLUMN `operator_id` BIGINT UNSIGNED NULL COMMENT '操作人用户主键',
  MODIFY COLUMN `operator_name_snapshot` VARCHAR(100) NULL COMMENT '生命周期操作人姓名快照',
  MODIFY COLUMN `event_detail` VARCHAR(1000) NULL COMMENT '生命周期事件详细说明',
  MODIFY COLUMN `occurred_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '事件发生时间';

ALTER TABLE `led_metric_snapshot`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `agent_id` BIGINT UNSIGNED NOT NULL COMMENT '关联智能体主键',
  MODIFY COLUMN `period_start` DATETIME(3) NOT NULL COMMENT '统计周期开始时间',
  MODIFY COLUMN `period_end` DATETIME(3) NOT NULL COMMENT '统计周期结束时间',
  MODIFY COLUMN `call_count` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '统计周期内调用次数',
  MODIFY COLUMN `alarm_count` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '统计周期内告警次数',
  MODIFY COLUMN `online_instance_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '正常在线实例数量',
  MODIFY COLUMN `total_instance_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '运行实例总数',
  MODIFY COLUMN `synced_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '数据最近同步时间';

ALTER TABLE `led_resource_link`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `agent_id` BIGINT UNSIGNED NOT NULL COMMENT '关联智能体主键',
  MODIFY COLUMN `resource_name_snapshot` VARCHAR(200) NOT NULL COMMENT '对接资源名称快照',
  MODIFY COLUMN `owner_name_snapshot` VARCHAR(50) NULL COMMENT '资源负责人姓名快照',
  MODIFY COLUMN `owner_phone_snapshot` VARCHAR(20) NULL COMMENT '资源负责人联系方式快照',
  MODIFY COLUMN `link_note` VARCHAR(500) NULL COMMENT '资源对接补充说明',
  MODIFY COLUMN `linked_at` DATETIME(3) NOT NULL COMMENT '资源建立对接时间',
  MODIFY COLUMN `unlinked_at` DATETIME(3) NULL COMMENT '资源解除对接时间';

ALTER TABLE `led_risk_answer`
  MODIFY COLUMN `assessment_id` BIGINT UNSIGNED NOT NULL COMMENT '关联风险评定主键',
  MODIFY COLUMN `question_id` BIGINT UNSIGNED NOT NULL COMMENT '关联风险问卷题目主键',
  MODIFY COLUMN `option_id` BIGINT UNSIGNED NOT NULL COMMENT '关联问卷选项主键';

ALTER TABLE `led_risk_assessment`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `assessment_no` VARCHAR(50) NOT NULL COMMENT '风险评定业务编号',
  MODIFY COLUMN `agent_id` BIGINT UNSIGNED NOT NULL COMMENT '关联智能体主键',
  MODIFY COLUMN `decision_basis` VARCHAR(500) NOT NULL COMMENT '风险等级自动判定依据',
  MODIFY COLUMN `submitted_by` BIGINT UNSIGNED NOT NULL COMMENT '提交人用户主键',
  MODIFY COLUMN `submitted_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '提交时间',
  MODIFY COLUMN `confirmed_by` BIGINT UNSIGNED NULL COMMENT '二次确认用户主键';

ALTER TABLE `led_risk_option`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `question_id` BIGINT UNSIGNED NOT NULL COMMENT '关联风险问卷题目主键',
  MODIFY COLUMN `option_text` VARCHAR(500) NOT NULL COMMENT '问卷选项内容';

ALTER TABLE `led_risk_question`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录主键',
  MODIFY COLUMN `question_code` VARCHAR(20) NOT NULL COMMENT '风险问卷题目编码',
  MODIFY COLUMN `question_text` VARCHAR(500) NOT NULL COMMENT '风险问卷题目内容',
  MODIFY COLUMN `sort_no` INT UNSIGNED NOT NULL COMMENT '显示排序号',
  MODIFY COLUMN `status` VARCHAR(20) NOT NULL DEFAULT 'ENABLED' COMMENT '题目状态：ENABLED启用、DISABLED停用',
  MODIFY COLUMN `effective_from` DATE NOT NULL COMMENT '题目生效日期',
  MODIFY COLUMN `effective_to` DATE NULL COMMENT '题目失效日期';

ALTER TABLE `sys_department`
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间',
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '记录最后更新时间',
  MODIFY COLUMN `is_deleted` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '科室逻辑删除标记：FALSE未删除，TRUE已删除';

ALTER TABLE `sys_file_object`
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '文件上传时间',
  MODIFY COLUMN `deleted_at` DATETIME(3) NULL COMMENT '文件逻辑删除时间';

-- 3. 记录修复版本
INSERT INTO `sys_schema_version` (`version_no`, `script_name`, `description`)
VALUES ('1.0.1', '医疗智能体管理平台_表和字段备注修复_V1.0.1.sql', '补齐全部表和字段的中文备注') AS `new`
ON DUPLICATE KEY UPDATE
  `script_name` = `new`.`script_name`,
  `description` = `new`.`description`;

-- 4. 执行后核验：预期均为0
SELECT COUNT(*) AS `无表备注数量`
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_TYPE = 'BASE TABLE' AND TABLE_COMMENT = '';

SELECT COUNT(*) AS `无字段备注数量`
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE() AND COLUMN_COMMENT = '';
